language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"

install: pip install -q $DJANGO flake8 coveralls

script: python -Wonce `which coverage` run runtests.py

after_success:
  - flake8
  - coverage report -m
  - coveralls